next-ver 1st upstream pull (#148)
* Pulling from upstream

* Bump WAF version (#1768)

* Add exceptions to active span during ASP.NET Web API 2 message handler exception (#1734)

At least one scenario has been identified today where an exception is thrown during while handling an ASP.NET Web API 2 request and we are unable to attach the error to our automatic instrumentation spans. This occurs when the application registers custom message handlers in the ASP.NET Web API 2 and the message handlers throw exceptions (before reaching the Api controllers). The result is that there was no `aspnet-webapi.request` span and the `aspnet.request` root span only sees the 500 status code because the exception was handled by the ASP.NET Web API 2 pipeline before returning.

Add an automatic instrumentation method into the global error handling of ASP.NET Web API 2 applications. When an exception is detected by the Web API 2 pipeline, the registered `IExceptionHandler` singleton is invoked before returning the request to the server, so we hook into that call to grab the exception object and attach it to the active span.

Note: This exception handling also applies to OWIN applications running Web API 2 endpoints, so once we automatically instrument OWIN applications to generate root spans this feature will come along for free.

```
Tags: {
  error.msg: The HTTP response has status code 500.
}
```

```
Tags: {
      error.msg: Passed in value was not 'true': false,
      error.stack:
System.ArgumentException: Passed in value was not 'true': false
at Samples.AspNetMvc5.Controllers.ApiController.TransientFailure(String value),
      error.type: System.ArgumentException,
}
```

This has been confirmed with the following test cases, on both ASP.NET Web API 2 applications and OWIN Web API 2 applications:
1. Adding a global message handler
2. Adding a per-route message handler

[1] https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/http-message-handlers
[2] https://docs.microsoft.com/en-us/aspnet/web-api/overview/error-handling/web-api-global-error-handling

* Ensure that ILogger sample version is bumped (#1770)

* Fixing empty payload to backend. If manuel reset event is not reset first, wait doesnt wait.. (#1758)

* Post code coverage comparison as a comment on PRs (#1704)

* Extract DownloadAzureArtifact to helper function

* Add Nuke build target for downloading coverage reports from Azure Devops to GitHub and comparing them

* Add to ultimate pipeline, to post directly from azdo

It's all a bit weird and roundabout, but it works...

* Don't require completed builds only for current artifacts

* Fix integration test name failing re-publish when re-running flakey tests

* Tweak display of coverage report

* Update comparison to include exact commit

* Minor fixes

* Restore accidentally deleted sdk install

* Address PR Feedback

* Fix CIAPP CIEnvironmentVariableTests (#1765)

* Ensure the PInvoke maps rewrites on some CallSite scenarios. (#1771)

* Add support for GraphQL 3 and 4 (#1751)

* Catch object disposed exception in Samples.HttpMessageHandler (#1774)

Likely culprit for test failures in the execution benchmarks (only happens on .NET 5 interestingly)

* Used the parsed version of the query string (#1777)

Used the parsed version of the query string

APPSEC-1404

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

* [Shared-Loader] - Add support for Module Entrypoint rewriting and .NET 4.5 fix (#1755)

* Add support for Module Entrypoint rewriting and .NET 4.5 fix

* Add environment variables to control loader options

* Fix warnings and linux build

* Debug logs on flat layout

* testing a change in the algorithm for flat layout

* Moar debugging data

* Add missing LogDebugIsEnabled flags

* Change feature flags to follow the tracer pattern

* update code owners (#1750)

* Update CODEOWNERS (#1785)

* Update .NET SDK to 5.0.401 (#1782)

* Update SDK version to 5.0.401

* Fix build_in_docker.sh script

* Update version of alpine

alpine 3.12 is no longer supported by .NET 5. Update to 3.14 (which will be lowest supported for .NET 6)

* Disable Verify's clipboard and diff tool integration

Causes failures in Alpine as the xsel tool isn't available

* Try downgrading alpine for now

* Rename ADO.NET providers integration name (#1781)

* Rename provider integration names to ADO.NET to use the same behavior as CallSite.

* Removes IntegrationName from IAdoNetClientData

* Refactor InstrumentationDefinitions generator (#1780)

* Refactor InstrumentationDefinitions generator.

* Update tracer/build/_build/PrepareRelease/GenerateIntegrationDefinitions.cs

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

* Add support for Elasticsearch 7 (#1760)

* Fix percentages in coverage report (#1793)

* Fix percentages in coverage report

* Include a link to the online Code Coverage report in the code coverage comparison comment

* Increase timeout in MassTransit smoke tests (#1779)

* Don't duplicate DB context configuration in MassTransit config

* Remove unused variable

* Try increasing command timeout to avoid flaky test

* Enable shared logger for managed log file (#1788)

`shared: true` should be set when multiple process may write to the managed log file.

* Clean up old benchmark branches (#1792)

This will automatically delete all but the specified "baseline" branch (1.27.1 currently) and the most recent 2 branches (the previous, plus the newly created benchmark branch) when auto-tagging the version bump commit.

This should ensure we only have 3 active benchmark branches at any one time, reducing the burden on CI

(The bash manipulation and renaming logic has all been tested and run locally)

* Fix the reference to mscorlib (#1797)

* Env var to override default AppSec rules (#1757)

Allow users to specify their own rules file to change how AppSec will analyze request.

Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>

* Fix indentation in yaml (#1801)

* Fix duplicating integrations due to multiple Initialize calls from different AppDomains. (#1794)

* Fix duplicating integrations due to multiple AppDomains.
Fix memory leak on NativeCallTargetDefinition disposal.

* Add comments.

* fix locks.

* Restore Tracer.ActiveScope in ASP.NET when request switches to a different thread (#1783)

## Issue
The existing ASP.NET instrumentation uses an HttpModule to handle the BeginRequest event at the beginning of a request. The callback creates a new scope, stores it in the execution context via `Tracer.ActiveScope`, and stores it inside the `HttpContext.Items` dictionary. Except for a few integrations like ASP.NET MVC, ASP.NET Web API 2, and WCF, all other integrations will only correlate their spans to the root span when the `Tracer.ActiveScope` property (which uses the execution context) is populated.

The issue is that ASP.NET may switch threads when handling requests. When it does this, it will correctly set the `HttpContext.Current` property on the new thread but the execution context of the new thread IS NOT identical to the previous execution context, causing `Tracer.ActiveScope` to be `null` or possibly incorrect.

## Fix
The fix is to add additional automatic instrumentation in the request pipeline to reset the `Tracer.ActiveScope` property. We've identified that the methods `System.Web.ThreadContext.AssociateWithCurrentThread` and `System.Web.ThreadContext.DisassociateFromCurrentThread` are responsible for managing HttpContext assignments, so these methods can be instrumented to extract the scope placed in the HttpContext and appropriately store/remove the `Tracer.ActiveScope`.

## Changes
- Add CallSite and CallTarget instrumentation on the following `System.Web` methods:
  - `System.Web.ThreadContext.AssociateWithCurrentThread`: Gets the scope from the `HttpContext.Items` dictionary and sets the `Tracer.ActiveScope` property
  - `System.Web.ThreadContext.DisassociateFromCurrentThread`: Unsets the `Tracer.ActiveScope` property
- Add a regression test that deterministically forces a thread switch and ensures that the two spans are included in the same trace

* Additional update to Web Api 2 tests (#1772)

This is a continuation of PR https://github.com/DataDog/dd-trace-dotnet/pull/1734 to ensure that we test the same routes in both the OWIN Web API 2 sample and the ASP.NET Web API 2 sample.

Changes:
- Add message handler requests to the OwinWebApi2 test cases with updated snapshots
- Add expected span counts to the test cases to ensure the test waits for the proper amount of spans from the MockTraceAgent

* Azure Functions Instrumentation (#1613)

* Azure Functions Instrumentation

* Share code between diagnostic observer and middleware instrumentation

* Use generic constraint

* Skip diagnostic observer in functions

* Rebase and new instrumentation definitions structure

* Remove unused class

* New API

* Missed sharing RequestTrackingFeature

* Use the "root" service name in all ILogger Logs (#1798)

Previously we were using the active span's service name in the logs.
In other ILogger injectors we only use the "application"  service name.
This updates the ILogger integration to do the same.

* Fix a path in debug build of managed loader which is required after the recent repo restructure. (#1806)

* Stop copying profiler/tracer home to test directories (#1808)

* Add steps to clean the packages directory and obj files

This is a horrible hack to try and get some space back in our integration and regression tests. But sometimes you gotta do whatcha gotta do.

* Remove unused methods

* Fix incorrect path in GetProfilerProjectBin()

* Assume that we always have the tracer home directory (which can be overriden set with the environment variable TracerHomeDirectory

I decided _not_ to just use the default DD_DOTNET_TRACER_HOME here, as thought it might cause extra confusiong for local testing, but I'm open to suggestions on this one

Note that this requires you run `build BuildTracerHomer` before running integration tests _even in Visual Studio_ etc. This is not ideal, but was the quickest solution for now

* Stop copying the profiler around in integration tests etc

Removed all these properties:
ExcludeManagedProfiler
ExcludeNativeProfiler
LoadManagedProfilerFromProfilerDirectory
ManagedProfilerOutputDirectory
ProfilerOutputDirectory

* Don't reference Datadog.Trace indirectly in the AutomapperTest project

* Revert "Add steps to clean the packages directory and obj files"

This reverts commit 7fc1c101b6ff1105bce328ea3aa5e73eeefee3cb.

* Fix default env vars in docker-compose

* Fix Arm64 reference

* Remove unused variables

* Fix alpine Waf copying wrong version into tracer home

* Store benchmark results as an artifact (#1799)

* Add json exporter to benchmarks

* Upload benchmark results as an artifact for later processing

* Ignore the build_data folder (used in CI)

* Add default exporters

* Remove manual exporters

* Fix exporter

* [Appsec] Fix posting json missing with HttpStreamRequest: missing header / reset streams (#1778)

* Fixed postjson for HttpStreamRequest

* Fix headers

* Request could be null if nothing has been posted

* No need for headers

* using stringbuildercache

* missing implementation

* Changing logging request in case of error

* remove request content implementation

* removing impl from benchmark

* - local function to static function to avoid capturing
- request turned to local object
- some omitted config await false

* Missing configure await false

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

* Fix Execution Benchmarks job filepath (#1810)

* Fix tracer path

* Ensure all sdks are installed.

* Update test spans from Crank runs (#1592)

Changes crank spans in the following ways:
- Sets tag `env=ci`
- Add `Crank.` prefix to the "Test Suite". For example, `calltarget.linux_arm64.arm64` will become `Crank.calltarget.linux_arm64.arm64`

* Add a native API to parse boolean environment variable values (#1815)

* Don't copy the logs for benchmarks (#1814)

Apparently it takes 15 mins to copy them!

* [app sec] fix bug when debug logs are enabled (#1796)

* Fix a bug where app sec failed in debug log mode because of a failure formatting a value

Also,

- Move some logs over to structured logging
- Remove native log for dlerror
- Use http for samples

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

* Parallelize throughput tests (#1773)

* Small fix for some paths in _build.csproj (#1812)

* Fix some paths in _build.csproj since folders structure has changed

* Propagate sampling priority to all spans during partial flush (#1803)

* JITInline callback refactor to fix race condition. (#1823)

* Restore the original env-var value before asserting. (#1816)

* Restore the original env-var value before the assert

* fix test

* Changes from review.

* Fixes the test when dogfooding CIApp with a custom AgentUri

* Update tracer/test/Datadog.Trace.Tests/Configuration/ConfigurationSourceTests.cs

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>

* Fix elasticsearch v7 and GraphQL file locations (#1821)

I think these must have got messed up during a rebase after the directory move

* Disable memory dumps in CI (#1822)

* Env var prefix rename

* Fix ctx propagation in AspNetCoreHttpRequestHandler

* Add using static to AspNetCoreDiagnosticObserver

* Use TraceId to create SpanContext

* Only set TestAllPackageVersions to true when needed

* Update integrations.json

* Update minimal pipeline per upstream changes

* Update GH workflow per upstream updates

Co-authored-by: Robert Pickering <robert.pickering@datadoghq.com>
Co-authored-by: Zach Montoya <zach.montoya@datadoghq.com>
Co-authored-by: Andrew Lock <andrew.lock@datadoghq.com>
Co-authored-by: Anna <anna.yafi@datadoghq.com>
Co-authored-by: Tony Redondo <tony.redondo@datadoghq.com>
Co-authored-by: Kevin Gosse <krix33@gmail.com>
Co-authored-by: Lucas Pimentel-Ordyna <lucas.pimentel@datadoghq.com>
Co-authored-by: Colin Higgins <colin-higgins@users.noreply.github.com>
Co-authored-by: macrogreg <macrogreg@users.noreply.github.com>